services:
  - type: web
    name: springboot-webapi
    env: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/webApi-0.0.1-SNAPSHOT.jar"
    plan: free
    region: oregon